### ISSUE TITLE
flextable rowheight

### ISSUE THREAD

**Issue by jmdeke** [davidgohel/flextable#179] opened 2020-01-28 08:47 UTC
Hi,

I recently updated my flextable from 0.5.5 to 0.5.6 and now all my functions to format the tables seem to be _broken_.
I figured out that in 0.5.5 a flextable's Row Height in the table properties was always set to "At least" but now in 0.5.6 it is set to "Exactly" (see image below):

![03_selecting_exactly](https://user-images.githubusercontent.com/60382624/73248561-79678400-41b3-11ea-952f-c1910ec3f0da.png)

I attached 2 images of how my tables looked like in a word document using 0.5.5 and 0.5.6.

Maybe you can add some option in the _height_all_ function to set this option in the table properties to "Exactly" or "At least"?

Do you think this is a bug, something you can fix or will be have to use this "fixed" height option from now on? 

I'm using the latest version or R (3.6.2 and RStudio latest version too, but I also tried 3.6.1 and the same thing happened).
If you cannot recreate this I can DM you one of my functions but from what I tested it happens the second a flextable is created (even before an _autofit_ or _height_all_..).

Regards.

![flextable055](https://user-images.githubusercontent.com/60382624/73248395-31486180-41b3-11ea-94a3-5bc24def1597.PNG)
![flextable056](https://user-images.githubusercontent.com/60382624/73248398-31e0f800-41b3-11ea-9372-64271aae6f12.PNG)

**Comment by davidgohel** [comment] 2020-01-28 09:11
Thanks,

This is a duplicate of #167

I am trying to find a nice solution to satisfy all people (those who want, 'at least', those who want 'exact', those who don't want any height to be defined) and will probably have something soon

**Closed by davidgohel** 2020-01-28 09:11 UTC

**Comment by davidgohel** [comment] 2020-01-28 09:21
> Maybe you can add some option in the height_all function to set this option in the table properties to "Exactly" or "At least"?

yes I think I like that solution :)

**Comment by davidgohel** [comment] 2020-01-28 09:23
(very nice table BTW!) did you use `compose` or did you format the data.frame before in your code?

**Comment by jmdeke** [comment] 2020-01-28 13:01
Sorry I didn't see that someone else had already posted about this. Good to see it is already being worked on!
For the table I actually format the data.frame object beforehand, so things like the _score_ variable are quickly done with a `paste`. But now that I see what `compose` does I might just start using that from now on, thanks!
