### ISSUE TITLE
Escape characters (Unicode sequences \uxxxx) in column names make flextable crush

### ISSUE THREAD

**Issue by LukaszDerylo** [davidgohel/flextable#291] opened 2021-02-02 09:37 UTC
Supose, I have a data frame:
`df<-data.frame(x=1:3, y=4:6)`
 
and I wish to put some `\uxxxx` sequences to it's column names:
```
(nm<-c('x\u00b2', 'y\u2082'))
"x²" "y₂"
 
colnames(df)<-nm
```

Now `flextable` fails:
```
flextable(df)
Error in `[.data.frame`(data, col_keys) : undefined columns selected
```

I believe it is because `\uxxxx` sequences are kept in `names(df)` (a default value of `col_keys` in `flextable()`)

```
names(df)
 "x²" "y₂"
```

But are not kept in `print(df)`:
```
 df
  x2 y2
1  1  4
2  2  5
3  3  6
```

**Comment by davidgohel** [comment] 2021-02-02 10:06
Please follow the guidelines you deleted when you open the issue form!

First, there are functions in flextable to handle names. It's start here: https://ardata-fr.github.io/flextable-book/layout-1.html#change-header-labels

Also, it looks like a duplicate of #268. Read this: https://github.com/davidgohel/flextable/issues/268#issuecomment-749231388

Why doing the formatting in the data.frame? Are your data manipulation easier when you use these column names? Why don't you want to use the recommendations that are in the documentation?

**Comment by LukaszDerylo** [comment] 2021-02-02 10:28
I'll start with #268 . It deals with Unicodes inside table, not in column names. So I can't make use of it (it's `col_keys` parameter that causes an error I'm trying to deal with)

`set_header_labels()` you mention in your first link is great as long as you deal with single table. Things get complicated when you wish to use it in a loop or in a function and simply can't correct header labels in each table by hand.

**Comment by davidgohel** [comment] 2021-02-02 11:02
No, column names are also in the discussion!

-----

I am trying to understand. You can do 

```
nm<-c('x\u00b2', 'y\u2082')) 
colnames(df)<-nm
```

But the following is not possible?

```
set_header_labels(
  ft,
  values = structure(
    c('x\u00b2', 'y\u2082'),
    names = c('x', 'y')
  )
)
```

(I must assume you are using R for Windows). 

Is it because you get the data pre-formatted? If it is the case, I have no solution. You saw the information is lost, you reported these column names are not kept by R itself. I don't know how to get them if they are not available. 

> Things get complicated when you wish to use it in a loop or in a function and simply can't correct header labels in each table by hand.

I do most of my flextable work with functions and loops... `set_header_labels` and all other functions that manage headers are usable in functions. Can you provide some code or more detail about that?

**Comment by LukaszDerylo** [comment] 2021-02-02 11:43
Yes, my data are pre-formatted. And there are plenty of them. So it's "no solution" case, I think...

**Comment by davidgohel** [comment] 2021-02-02 11:56
Please next time, really follow the guidelines. 

You have started with "I wish to put some \uxxxx sequences to it's column names" but ended saying "the data are pre-formatted". It's a waste of time for you and me.

**Closed** 2021-02-02 11:56 UTC
Labels: invalid
