### ISSUE TITLE
package or namespace load failed for 'flextable' in quarto document

### ISSUE THREAD

**Issue by ronald-vrablicz-gf** [davidgohel/flextable#649] opened 2024-08-07 11:04 UTC
After setup of a new Laptop where I installed R 4.4.1 and RStudio 2024.04.2 I had to see that

- the flextable library (0.9.6) produces an error when it is attached in a quarto document (.qmd) but
- there is no problem when it is attached in a RMarkdown document (.Rmd).

The error occurs immediately after klicking the render button of a .qmd file and looks like this:

> Quitting from lines 8-9 [setup] (flextable_test.qmd)
> Error:
> ! package or namespace load failed for 'flextable':
>  .onLoad failed in loadNamespace() for 'shiny', details:
>   call: .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version)
>   error: invalid non-character version specification 'x' (type: double)
> Backtrace:
>  1. base::library(flextable)
>  2. base::tryCatch(...)
>  3. base (local) tryCatchList(expr, classes, parentenv, handlers)
>  4. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
>  5. value[[3L]](cond)

That error is reproducable by creating a new quarto document which looks like that  

```
---
title: "flextable_test"
format: html
editor: visual
---


```{r setup}
library(flextable)
```

I also read previous similar issues and installed the actual development version 0.9.7.005 but this does not solve the problem.

my sessionInfo():

R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252    LC_MONETARY=German_Austria.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Austria.1252    
system code page: 65001

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.9.7.005

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.8          compiler_4.4.1          crayon_1.5.2            promises_1.2.0.1        zip_2.1.1               Rcpp_1.0.7             
 [7] xml2_1.3.2              stringr_1.5.1           later_1.2.0             fontquiver_0.2.1        textshaping_0.3.6       systemfonts_1.0.4      
[13] uuid_0.1-4              fastmap_1.1.0           mime_0.10               R6_2.5.1                gfonts_0.2.0            gdtools_0.3.7          
[19] generics_0.1.3          curl_5.2.1              knitr_1.45              openssl_2.0.3           crul_1.1.0              lubridate_1.9.3        
[25] shiny_1.7.4             rlang_1.1.1             httpcode_0.3.0          stringi_1.8.3           httpuv_1.6.1            xfun_0.42              
[31] timechange_0.3.0        cli_3.6.2               magrittr_2.0.1          grid_4.4.1              digest_0.6.27           rstudioapi_0.13        
[37] xtable_1.8-4            askpass_1.1             lifecycle_1.0.4         evaluate_0.24.0         glue_1.6.2              data.table_1.14.2      
[43] officer_0.6.6           fontLiberation_0.1.0    ragg_1.2.5              fontBitstreamVera_0.1.1 rmarkdown_2.27          tools_4.4.1            
[49] ellipsis_0.3.2          htmltools_0.5.4

**Comment by ronald-vrablicz-gf** [comment] 2024-08-07 11:41
I don't know what exactly happens here, but after upgrading shiny to 1.9.1 the problem seems to be solved.
Now I do not receive an error message. :-)

**Comment by davidgohel** [comment] 2024-08-12 17:26
hello and thanks,

I was not able to reproduce and it seems it is solved on your side so I am closing the issue.

**Closed by davidgohel** 2024-08-12 17:25 UTC
