### ISSUE TITLE
https hyperlinks get broken in powerpoint containing a flextable with hyperlinks

### ISSUE THREAD

**Issue by ktitov** [davidgohel/flextable#310] opened 2021-04-28 09:51 UTC
Hi, 
https:// hyperlinks get broken when exporting the powerpoint containing a flextable with those hyperlinks.
Here's a reprex:
```
library(officer)
library(flextable)

t <- data.frame(col = "https://www.bbc.com/news", href = "https://www.bbc.com/news")

ft <- flextable::flextable(t)
ft <- flextable::compose(x = ft, 
                           j = "col", 
                           value = flextable::as_paragraph(
                             flextable::hyperlink_text(x = `col`, url = `href`)
                           ))
p <- read_pptx()
p <- add_slide(p)
p <- ph_with(p, ft, location = ph_location_type(type = "body"))
print(p, "reprex_pres.pptx")
```

If you check the `ft` table before export, it has the correct link in `col` column and it works when you click on it.
But when you look in the exported powerpoint, the link becomes 
https%3A//www.bbc.com/news
And it does not work when you try to click it. 

Any idea where the links get broken?

Thanks!
K

**Comment by davidgohel** [comment] 2021-04-28 09:58
thanks

duplicate of #297

**Comment by davidgohel** [comment] 2021-05-17 12:29
Sorry, you are right, it's different from the 297.

**Comment by cavamic** [comment] 2021-10-29 18:06
Hi David - I see this bug has been closed but still getting the same issue as the initial reprex. Just wondering if this bug has been fixed or still a 'to-do'. 

Much appreciated!

**Comment by victorcaquilpan** [comment] 2021-11-17 12:56
This issue happens also in word output. Anyone know a solution?

**Comment by davidgohel** [comment] 2021-11-17 14:02
I can't reproduce @victorcaquilpan, the code in the issue is producing the expected result. 

```r
library(officer)
library(flextable)

t <- data.frame(col = "https://www.bbc.com/news", href = "https://www.bbc.com/news")

ft <- flextable::flextable(t)
ft <- flextable::compose(x = ft, 
                         j = "col", 
                         value = flextable::as_paragraph(
                           flextable::hyperlink_text(x = `col`, url = `href`)
                         ))

print(ft, preview = "docx")
```

[aaa.docx](https://github.com/davidgohel/flextable/files/7555118/aaa.docx)


So, update your packages versions, and provide a reproducible example + the `sessionInfo()` if you still think you have a bug.

**Comment by davidgohel** [comment] 2021-11-17 14:04
Same comment @cavamic. Update your packages versions, and provide a reproducible example + the `sessionInfo()`.

**Comment by cavamic** [comment] 2021-11-17 15:25
Thanks David - 

I get an error running your reprex 
`Error in strsplit(URL, "") : non-character argument`

But was able to get it working by specifying the URL. I also changed to print to PPTX. 

```
library(officer)
library(flextable)

t <- data.frame(col = "https://www.bbc.com/news", href = "https://www.bbc.com/news")

ft <- flextable::flextable(t)
ft <- flextable::compose(x = ft, 
                         j = "col", 
                         value = flextable::as_paragraph(
                           flextable::hyperlink_text(x = `col`, url = "https://www.bbc.com/news")
                         ))

print(ft, preview = "pptx")
```
In the attached pptx the colon has been translated to %3A and corrupts the link. 

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.6.10 officer_0.4.1    FactSet3_3.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        digest_0.6.27     R6_2.5.1          evaluate_0.14     zip_2.2.0         rlang_0.4.11      gdtools_0.2.3    
 [8] uuid_0.1-4        data.table_1.14.0 xml2_1.3.2        rmarkdown_2.11    tools_3.6.3       xfun_0.23         compiler_3.6.3   
[15] systemfonts_1.0.2 base64enc_0.1-3   htmltools_0.5.1.1 knitr_1.36  
```    

Much appreciated. 


[reprex.pptx](https://github.com/davidgohel/flextable/files/7555732/reprex.pptx)

**Comment by victorcaquilpan** [comment] 2021-11-17 18:42
Hello @davidgohel 

I was using rmarkdown::word_document() to render my document, however, I saw [this ebook](https://ardata-fr.github.io/flextable-book/rendering.html) (chapter 3.3.5) about flextable, which indicates that I need to use officedown::rdocx_document to render links in a word document. I am utilising it, but I obtained another issue. When I render the document, the hyperlink appears in a weird way. It combines my local working directory path with the hyperlink. I show an image about this issue.

![imagen](https://user-images.githubusercontent.com/7284785/142262057-d8b24b73-4741-463c-92bd-2145f91dd78f.png)

You can see that the first part of the hyperlink is my local working directory and the last part is the BBC page. I think the problem could be that I am working in a external location (external disk). This issue is generated using this code:

```
library(officer)
library(flextable)

t <- data.frame(col = "https://www.bbc.com/news", href = "https://www.bbc.com/news")

ft <- flextable::flextable(t)
ft <- flextable::compose(x = ft, 
                         j = "col", 
                         value = flextable::as_paragraph(
                           flextable::hyperlink_text(x = `col`, url = `href`)
                         ))
ft
```

**Comment by davidgohel** [comment] 2021-11-17 19:59
thank you @cavamic, It may be only an issue on Windows... 

@victorcaquilpan, I can't say if it is related or not, but I am sure that working with UNC is not really compatible with R, git and probably many other tools.

**Comment by gregleleu** [comment] 2022-05-28 17:45
I have the same/similar issue, URL are aggressively encoded here https://github.com/davidgohel/flextable/blob/293c861c25ab1a1d15390dacd1034f21582d0884/R/pptx_str.R#L55
https://www.google.com
becomes
https%3A//www.google.com

Powerpoint is able internally to figure it out, but when I export to pdf, Preview (I'm on a mac) won't convert the encoded back to the original.

The code is using htmltools::urlEncodePath, which is more aggressive than base::URLencode. In my fork URLencode works fine (both with powerpoint and pdf exports)

What was the reason behind urlEncodePath? URL encoding is often tricky maybe the least aggressive version is better and lets the end-user deal with complex cases (e.g. needing to encode nested cases)

**Closed** 2022-05-29 21:03 UTC
Labels: bug

**Comment by davidgohel** [comment] 2022-05-29 21:09
@gregleleu I just post a fix. I think you are right, URL encoding is an issue since a long time, probably because it should not occur! 

This version does not encode any URL and keep them 'as is'. Can you let me know if it fixes your issue? If not, I will reopen this issue.

I think it should also fix the issue of some windows user that see a link to their drive instead of the real link as shown here: https://github.com/davidgohel/flextable/issues/297#issuecomment-803054896

![](https://user-images.githubusercontent.com/32994/111831198-4f10e280-88ef-11eb-9ed4-894941ec6a4f.png)
