### ISSUE TITLE
as_raster() doesn't work when setting webshot="webshot2".

### ISSUE THREAD

**Issue by yanxianl** [davidgohel/flextable#318] opened 2021-05-20 17:01 UTC
Hi, I have a problem when trying to call webshot2 from the `as_raster()` function. The code seemed to run forever. R crashed when I terminated the code. I tried to capture the bug using reprex but it didn't work. Below is a minimal example:
``` r
library(dplyr)
library(flextable)
require(webshot2)

ft <- iris %>% 
  group_by(Species) %>% 
  summarise_all(median) %>% 
  flextable()  

ft_ws <- as_raster(ft, webshot="webshot") # works
#> Registered S3 method overwritten by 'webshot':
#>   method        from    
#>   print.webshot webshot2

ft_ws2 <- as_raster(ft, webshot="webshot2") # do not work; did not include in the reprex

sessionInfo()
#> R version 4.0.5 (2021-03-31)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19041)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> system code page: 936
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] webshot2_0.0.0.9000 flextable_0.6.5     dplyr_1.0.5        
#> 
#> loaded via a namespace (and not attached):
#>  [1] zip_2.1.1           Rcpp_1.0.6          later_1.2.0        
#>  [4] pillar_1.6.0        compiler_4.0.5      highr_0.9          
#>  [7] base64enc_0.1-3     tools_4.0.5         uuid_0.1-4         
#> [10] digest_0.6.27       jsonlite_1.7.2      evaluate_0.14      
#> [13] lifecycle_1.0.0     tibble_3.1.1        pkgconfig_2.0.3    
#> [16] rlang_0.4.11        reprex_2.0.0        cli_2.5.0          
#> [19] DBI_1.1.1           rstudioapi_0.13     magick_2.7.1       
#> [22] yaml_2.2.1          xfun_0.22           fastmap_1.1.0      
#> [25] xml2_1.3.2          officer_0.3.18      withr_2.4.2        
#> [28] stringr_1.4.0       knitr_1.33          generics_0.1.0     
#> [31] gdtools_0.2.3       fs_1.5.0            vctrs_0.3.8        
#> [34] systemfonts_1.0.1   webshot_0.5.2       websocket_1.4.0    
#> [37] tidyselect_1.1.1    chromote_0.0.0.9003 glue_1.4.2         
#> [40] data.table_1.14.0   R6_2.5.0            processx_3.5.2     
#> [43] fansi_0.4.2         rmarkdown_2.7       callr_3.7.0        
#> [46] purrr_0.3.4         magrittr_2.0.1      promises_1.2.0.1   
#> [49] ps_1.6.0            ellipsis_0.3.2      htmltools_0.5.1.1  
#> [52] assertthat_0.2.1    utf8_1.2.1          stringi_1.5.3      
#> [55] crayon_1.4.1
```

<sup>Created on 2021-05-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by davidgohel** [comment] 2021-05-25 08:48
I can't reproduce... It seems to me it's an issue you have with webshot2, maybe Chrome or something else but not related to flextable.

Could you try with a simple webshot2 example (without flextable)?

**Comment by yanxianl** [comment] 2021-05-26 09:56
Hi, thanks for the help in this difficult time! I could run webshot2 demo code without problems (reprex example below). I noticed that I could run ` ft_ws2 <- as_raster(ft, webshot="webshot2")`  in a new R sesstion but need to use a new variable name if I want to run the code again (e.g., ` ft_ws3 <- as_raster(ft, webshot="webshot2")` ). If I run the code again, R is stuck. When I tried to render RMardown, R was also stuck. I've also reported this problem at the webshot2 github repo.

``` r
library(webshot2)

# Specific height and width
webshot("https://www.r-project.org", vwidth = 1600, vheight = 900, cliprect = "viewport")
```

![](https://i.imgur.com/IenuaC1.png)

``` r
sessionInfo()
#> R version 4.0.5 (2021-03-31)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19041)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> system code page: 936
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] webshot2_0.0.0.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6          rstudioapi_0.13     knitr_1.33         
#>  [4] magrittr_2.0.1      R6_2.5.0            rlang_0.4.11       
#>  [7] fastmap_1.1.0       stringr_1.4.0       highr_0.9          
#> [10] tools_4.0.5         websocket_1.4.0     xfun_0.22          
#> [13] cli_2.5.0           withr_2.4.2         htmltools_0.5.1.1  
#> [16] yaml_2.2.1          digest_0.6.27       processx_3.5.2     
#> [19] later_1.2.0         fs_1.5.0            promises_1.2.0.1   
#> [22] ps_1.6.0            curl_4.3.1          glue_1.4.2         
#> [25] evaluate_0.14       rmarkdown_2.7       reprex_2.0.0       
#> [28] stringi_1.5.3       compiler_4.0.5      chromote_0.0.0.9003
#> [31] jsonlite_1.7.2
```

<sup>Created on 2021-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by davidgohel** [comment] 2021-12-19 18:24
I am closing that issue as I am not able to reproduce and nobody else ever reported this issue again. It is probably due to something related to local installation but not flextable that is only using a standard webshot function

**Closed by davidgohel** 2021-12-19 18:24 UTC
