### ISSUE TITLE
Bug with multiple lines

### ISSUE THREAD

**Issue by TobiSonne** [davidgohel/flextable#178] opened 2020-01-21 19:58 UTC
Hi, 

I want to have tables with multiple lines. 
```
library(data.table)
library(tidyverse) 
library(flextable) 

flexiris <- 
  iris %>% 
  as.data.table %>% 
  head %>% 
  .[, Species := str_c("1\n2\n3\n", Species)] %>% 
  flextable %>% 
  border(part = "all", border = fp_border()) %>% 
  autofit

flexiris

Document <- read_docx()
Dodument <- Document %>% body_add_flextable(flexiris)
print(Document, target = "Test.docx")
```

In RStudio everything works fine but when I print the flextables into a word document only the first line is shown.

![example](https://user-images.githubusercontent.com/34717432/72838351-6c690300-3c90-11ea-9bc4-d5b80c573742.jpg)

What can I do? I don't want to adjust the height manually with `height`. I think `autofit` should do this automatically. A solution would be great, it is really important for me. Thank you very much!

Edit:
I solved the problem with the following code:

```

xml.table <- str_replace_all(flextable:::docx_str.flextable(Test.Table), '\\"exact\\"', '\\"atLeast\\"')

Document <- officer:::body_add_xml(Document, str = xml.table, pos = "after")
```

Probably you could add this option to `body_add_flextable`?

**Comment by davidgohel** [comment] 2020-01-27 16:34
Thanks,

This is a duplicate of #167

**Closed by davidgohel** 2020-01-27 16:34 UTC
