### ISSUE TITLE
docx_value not included in latest CRAN package for Mac OS X

### ISSUE THREAD

**Issue by juanvivancot** [davidgohel/flextable#334] opened 2021-06-30 15:21 UTC
flextable::docx_value is not included in the package for MAC OS X hosted on Cran. I've tried reinstalling multiple times, but it's just simply not there.

**Comment by davidgohel** [comment] 2021-06-30 17:12
duplicate of #288

**Closed by davidgohel** 2021-06-30 17:12 UTC
Labels: duplicate

**Comment by vivancoCFE** [comment] 2021-07-08 11:24
Thank you! I should've have known this was the case.
