### ISSUE TITLE
Rscript crash

### ISSUE THREAD

**Issue by patriceorliange** [davidgohel/flextable#186] opened 2020-02-12 09:07 UTC
Bonjour David,

La fonction set_header_df() fait planter RGui/RScript.exe i386/x64 (pas de soucis sous RStudio par contre).

Windows R 3.6.2, flextable 0.5.7.005 (même problème avec 0.5.8.002)
Voici un code pour reproduire:
library(flextable)

df <- data.frame(Date=c('2010-01-01','2011-01-01'), V=c(9,10))

ft <- flextable(df)

z  <- data.frame(col_keys = colnames(df) ,labels = colnames(df),stringsAsFactors = FALSE)

ft <- set_header_df(ft, mapping = z)

Problem signature:
  Problem Event Name:                      APPCRASH
  Application Name:                           Rscript.exe
  Application Version:                         3.62.12024.0
  Application Timestamp:                   5df1fdf7
  **Fault Module Name:                        systemfonts.dll**
  Fault Module Version:                      0.0.0.0
  Fault Module Timestamp:                5dd52fa8
  Exception Code:                               c0000005
  Exception Offset:                              0000000000001597
  OS Version:                                       6.3.9600.2.0.0.16.7
  Locale ID:                                          1033
  Additional Information 1:                71bf
  Additional Information 2:                71bf74739ed0d1b09d4646a8fb208fbb
  Additional Information 3:                4976
  Additional Information 4:                4976e6f994a1d3d5a3ac88d74af36442
 

Exception thrown at 0x0000000064B01597 (systemfonts.dll) in Rgui.exe: 0xC0000005: **Access violation reading location** 0x0000000000000000.

0000000064B01563 and eax,0FFFFFED4h
0000000064B01568 mov byte ptr [rsp+50h],bpl
0000000064B0156D add eax,2BCh
0000000064B01572 mov byte ptr [rsp+51h],0
0000000064B01577 mov qword ptr [rsp+40h],0
0000000064B01580 mov dword ptr [rsp+48h],eax
0000000064B01584 call 0000000064B030C0
0000000064B01589 movsxd r8,dword ptr [rsp+0B0h]
0000000064B01591 mov rbx,rax
0000000064B01594 mov rcx,rsi
0000000064B01597 mov rdx,qword ptr [rax]
0000000064B0159A call 0000000064C14058
0000000064B0159F mov rcx,qword ptr [rbx]
0000000064B015A2 mov esi,dword ptr [rbx+8]
0000000064B015A5 test rcx,rcx
0000000064B015A8 je 0000000064B015AF
0000000064B015AA call 0000000064C7ED10
0000000064B015AF mov rcx,qword ptr [rbx+10h]
0000000064B015B3 test rcx,rcx
0000000064B015B6 je 0000000064B01640
0000000064B015BC call 0000000064C7ED10
0000000064B015C1 mov rcx,qword ptr [rbx+18h]

**Comment by davidgohel** [comment] 2020-02-15 10:26
I did run your example via Rscript and got no issue. My `sessionInfo() `was:

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.5.7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        digest_0.6.23     R6_2.4.1          magrittr_1.5      evaluate_0.14     zip_2.0.4         rlang_0.4.4      
 [8] gdtools_0.2.1     uuid_0.1-2        data.table_1.12.8 xml2_1.2.2        rmarkdown_2.1     tools_3.6.1       officer_0.3.6    
[15] xfun_0.12         compiler_3.6.1    systemfonts_0.1.1 base64enc_0.1-3   htmltools_0.4.0   knitr_1.28 
```


From what I can read, you have an issue with systemfonts, not flextable.

**Comment by davidgohel** [comment] 2020-03-04 11:03
I am closing that issue as I was not able to reproduce and got no answer. I think updating the package should solve that issue.

**Closed by davidgohel** 2020-03-04 11:03 UTC

**Comment by WPBoddy** [comment] 2020-03-06 17:25
David, I've also run into this error on R 3.6.2, both in Rgui and Rstudio. set_header_df() function crashes the session. No problem on R 3.6.0. Has this problem been addressed elsewhere? 

`####################################################
rm(list=ls())
library(flextable)
typology <- data.frame(
   col_keys = c( "Sepal.Length", "Sepal.Width", "Petal.Length",
                 "Petal.Width", "Species" ),
   what = c("Sepal", "Sepal", "Petal", "Petal", "Species"),
   measure = c("Length", "Width", "Length", "Width", "Species"),
   stringsAsFactors = FALSE )

ft <- flextable( head( iris ))
ft <- set_header_df(ft, mapping = typology, key = "col_keys" )
####################################################`

`> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.5.8

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        digest_0.6.24     R6_2.4.1          magrittr_1.5      evaluate_0.14     zip_2.0.4         rlang_0.4.4       gdtools_0.2.1    
 [9] uuid_0.1-2        data.table_1.12.8 xml2_1.2.2        rmarkdown_2.1     tools_3.6.2       officer_0.3.6     xfun_0.12         compiler_3.6.2 `

**Comment by davidgohel** [comment] 2020-03-06 17:34
No, this problem is not reproducible.

I di run test on a windows machine and could not reproduce. Same on rhub, same on CRAN

@WPBoddy How can you have gdtools_0.2.1 but not systemfonts? 

I think you don't have a standard installation. See https://cran.r-project.org/web/packages/gdtools/index.html, systemfonts is necessary.

**Comment by davidgohel** [comment] 2020-03-06 17:36
@WPBoddy can you also post the sessionInfo results you have with R 3.6.0?

**Comment by WPBoddy** [comment] 2020-03-06 18:28
Thank you for the prompt response. RE "How can you have gdtools_0.2.1 but not systemfonts?" I do not know the answer to this. I run 3.6.0 on my PC, where

####################################################
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] flextable_0.5.8     CPPsource_1.0       corrplot_0.84       readxl_1.3.1       
 [5] ggplot2_3.2.0       RODBC_1.3-15        doParallel_1.0.14   iterators_1.0.10   
 [9] foreach_1.4.4       Matrix_1.2-17       gridExtra_2.3       statmod_1.4.32     
[13] latticeExtra_0.6-28 RColorBrewer_1.1-2  lattice_0.20-38     sqldf_0.4-11       
[17] RSQLite_2.1.1       gsubfn_0.7          proto_1.0.0         dplyr_0.8.4        
[21] plyr_1.8.4          data.table_1.12.8   stringr_1.4.0       readr_1.3.1        
[25] nlme_3.1-140        R.methodsS3_1.7.1   markdown_1.0        shiny_1.3.2        

loaded via a namespace (and not attached):
 [1] bit64_0.9-7       jsonlite_1.6      assertthat_0.2.1  blob_1.1.1       
 [5] cellranger_1.1.0  gdtools_0.2.1     pillar_1.4.1      glue_1.3.1       
 [9] uuid_0.1-4        chron_2.3-53      digest_0.6.19     promises_1.0.1   
[13] colorspace_1.4-1  htmltools_0.3.6   httpuv_1.5.1      pkgconfig_2.0.2  
[17] purrr_0.3.2       xtable_1.8-4      scales_1.0.0      later_0.8.0      
[21] officer_0.3.7     tibble_2.1.3      withr_2.1.2       lazyeval_0.2.2   
[25] magrittr_1.5      crayon_1.3.4      mime_0.7          evaluate_0.14    
[29] memoise_1.1.0     xml2_1.2.2        tools_3.6.0       hms_0.4.2        
[33] munsell_0.5.0     zip_2.0.4         compiler_3.6.0    systemfonts_0.1.1
[37] rlang_0.4.2       grid_3.6.0        rstudioapi_0.10   rmarkdown_2.1    
[41] tcltk_3.6.0       base64enc_0.1-3   gtable_0.3.0      codetools_0.2-16 
[45] DBI_1.0.0         R6_2.4.0          knitr_1.28        bit_1.1-14       
[49] stringi_1.4.3     Rcpp_1.0.1        tidyselect_0.2.5  xfun_0.12  
####################################################   

As you can see, systemfonts is there. On the server running R 3.6.2, I installed and loaded systemfonts, updated gdtools and flextable, but the same crash occurs. I think I'm using CRAN mirror at https://mirrors.nics.utk.edu/cran/.

**Comment by davidgohel** [comment] 2020-03-07 06:38
@patriceorliange Can you also show your `sessionInfo()` for both R version 3.6.0 and 3.6.2?

**Comment by WPBoddy** [comment] 2020-03-09 17:27
@davidgohel Let me know how I can help debug this on my end. I've loaded the set_part_df() function (based on what I see here https://github.com/davidgohel/flextable/blob/master/R/set_headers.R

but it breaks when trying to evaluate complex_tabpart() because the function can't be found. I'm not sure if this is the same reason that set_part_df() crashes my R session, or if I'm making a mistake somewhere.

**Comment by patriceorliange** [comment] 2020-03-13 09:37
Here sessioninfo and searchpaths():
> library(flextable)
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64(build 9600)
 
Matrix products: default
 
locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                         
[5] LC_TIME=English_United States.1252   
 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
 
other attached packages:
[1] flextable_0.5.7.005
 
loaded via a namespace (and not attached):
[1] Rcpp_1.0.3        digest_0.6.23     R6_2.4.1          magrittr_1.5     
 [5] evaluate_0.14     zip_2.0.4         rlang_0.4.2       gdtools_0.2.1    
 [9] uuid_0.1-2        data.table_1.12.8 xml2_1.2.2        rmarkdown_2.0    
[13] tools_3.6.2       officer_0.3.7.012 xfun_0.11         compiler_3.6.2   
[17] systemfonts_0.1.1 base64enc_0.1-3   htmltools_0.4.0   knitr_1.26       
> searchpaths()
[1] ".GlobalEnv"                 "X:/R-ECO/library/flextable"
[3] "X:/R-ECO/library/stats"     "X:/R-ECO/library/graphics"
 [5] "X:/R-ECO/library/grDevices" "X:/R-ECO/library/utils"   
 [7] "X:/R-ECO/library/datasets"  "X:/R-ECO/library/methods" 
 [9] "Autoloads"                  "X:/R-ECO/library/base"    
>

**Comment by patriceorliange** [comment] 2020-03-13 09:37
Same in 3.6.3:

> library(flextable)   > sessionInfo()   R version 3.6.3 (2020-02-29)   Platform: x86_64-w64-mingw32/x64 (64-bit)   Running under: Windows   Server 2012 R2 x64 (build 9600)       Matrix products: default       locale:   [1] LC_COLLATE=English_United   States.1252    [2] LC_CTYPE=English_United   States.1252     [3] LC_MONETARY=English_United   States.1252   [4] LC_NUMERIC=C                            [5] LC_TIME=English_United   States.1252          attached base   packages:   [1] stats       graphics  grDevices utils     datasets  methods     base            other attached   packages:   [1] flextable_0.5.8       loaded via a   namespace (and not attached):   [1] Rcpp_1.0.3          digest_0.6.25       R6_2.4.1            magrittr_1.5         [5] evaluate_0.14       zip_2.0.4           rlang_0.4.4         gdtools_0.2.1        [9] uuid_0.1-2          data.table_1.12.8 xml2_1.2.2          rmarkdown_2.1       [13] tools_3.6.3         officer_0.3.7.012 xfun_0.12           compiler_3.6.3      [17] systemfonts_0.1.1 base64enc_0.1-3     htmltools_0.4.0   knitr_1.28          > searchpaths()   [1] ".GlobalEnv"                     "X:/R-ECO-TST/library/flextable"   [3] "X:/R-ECO-TST/library/stats"     "X:/R-ECO-TST/library/graphics"    [5] "X:/R-ECO-TST/library/grDevices" "X:/R-ECO-TST/library/utils"       [7] "X:/R-ECO-TST/library/datasets"  "X:/R-ECO-TST/library/methods"     [9] "Autoloads"                      "X:/R-ECO-TST/library/base"       >
--

**Comment by patriceorliange** [comment] 2020-03-13 09:38
I also post it here: https://github.com/r-lib/systemfonts/issues/20

**Comment by davidgohel** [comment] 2020-03-13 10:06
@patriceorliange I think the fact that your organisation is still using UNC (as we can see in the issue of systemfonts) is really not a good idea. R (and git, and RStudio) are not running perfectly on UNC. @WPBoddy your issue was that systemfonts was not installed. If after a clean installation, you still meet that issue, open a new issue (I don't think you could get message "Fault Module Name: systemfonts.dll" if systemfonts was not installed).

I am locking that issue also as it is more likely related to systemfonts than flextable.
