### ISSUE TITLE
borders: default value and importation

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/flextable#191] opened 2020-02-18 11:11 UTC
Hi David, 

I just noticed that, in all the `border` examples of the `flextable` package, you start by importing the `officer` package in order to use the `fp_border` function.

Wouldn't this function be more appropriate in the `flextable` package?

Also, the default value of several (maybe all?) `border` functions is NULL. Wouldn't it be more appropriate to have the default to `fp_border()`? Is there any reason one would call this function to set a null border?

For instance, this code 2nd line seems unnecessarily verbose to me:
```r
iris %>% head %>% flextable %>% hline(i=3) #no border is added
iris %>% head %>% flextable %>% hline(i=3, border=officer::fp_border()) 
```

Best regards,
Dan

**Comment by davidgohel** [comment] 2020-02-18 12:50
> Wouldn't this function be more appropriate in the flextable package?

No, as I need them in flextable/officedown, mschart, and non public packages (for customers)

> [...] seems unnecessarily verbose [...]

Yes, I agree; I can work on that later - or review a PR if you feel you have time;). 

Note I will take some time on officer soon to improve documentation and Word support. All objects `fp_` need a good documentation and explanation...

**Comment by DanChaltiel** [comment] 2020-02-18 14:16
Would you consider something like this in a pull request?

```
#' re-export fp_border
#'
#' @importFrom officer fp_border
#' @name fp_border
#' @export
NULL
```

This is similar to the `magrittr` pipe operator re-export that you can see at https://www.r-bloggers.com/re-exporting-the-magrittr-pipe-operator/.

I'd see this more the other way around (importing in `flextable::fp_border` in `officer` would make a little more sense to me) but if you have business constraints this is, of course, non-negotiable. I wonder if this would not come down to the same thing but you might not want to take that risk.

The 2 problems are intertwined as it would be very strange to have a function default value pointing to another package.

**Comment by davidgohel** [comment] 2020-02-18 14:26
> Would you consider something like this in a pull request?

Yes!


If you have a look at officer source here:
https://github.com/davidgohel/officer/blob/master/R/formatting_properties.R#L290

You will see that `fp_par` is using `fp_border`. That is one of the reason we need `fp_border` to be in officer. flextable imports officer, if officer also imports flextable, we will go in an infinite loop ;)

**Comment by DanChaltiel** [comment] 2020-02-18 16:10
I searched "fp_border" in the `officer` github, and it seems that it is only used as the default parameter of `fp_par` and some other functions. The default is a null border (with `width=0`) so this could be the other way around, with defaulting to null in `officer` instead of in `flextable`.

Since borders are mostly used in tables, rather than in paragraphs, I think it is more logical to have `fp_border` in the `flextable` package. Then, the `officer` package could use the above-mentioned re-export trick to call it in `fp_par` and its friends, avoiding an infinite loop.

However, this might be quite a large refactoring, perhaps worthy of consideration, but not necessarily wanted at this time.

I'm going to test the "simple" way in local and I'll get back to you with a pull request when I have some time :-)

**Comment by davidgohel** [comment] 2020-02-18 16:17
I don't want to import flextable to add a border in mschart.

**Comment by davidgohel** [comment] 2020-03-20 22:09
I am closing that issue as it is not a bug. 

In summary, to avoid typing `library(officer)` to be able to use `fp_border` you want to re export the function in `flextable`.

My opinion is that's not really necessary but if you send a PR, I'll accept it  as I don't think there is any impact or risk.

**Closed by davidgohel** 2020-03-20 22:09 UTC
Labels: enhancement
