### ISSUE TITLE
The output in R studio viewer is fine but shows weird changes in line widths when using browsers

### ISSUE THREAD

**Issue by akikatakada** [davidgohel/flextable#343] opened 2021-08-24 02:38 UTC
Hello, I was using flextable in my shinyapp and noticed that there are weird changes in line widths (or colour) when the table is viewed in a browser. After a few checks, I notice that the same issue exists even when it is no in shiny. Therefore, I suspect it is something to do with flextable and the browser, instead of shiny. I did a bit of search but didn't see anyone else asking similar questions.

Here I'm using the example given from the documentation

```
library(officer)
library(flextable)

big_border = fp_border(color="red", width = 2)
small_border = fp_border(color="gray", width = 1)

myft <- flextable(head(airquality))
myft <- border_remove(x = myft)
myft <- border_outer(myft, part="all", border = big_border)
myft <- border_inner_h(myft, part="all", border = small_border)
myft <- border_inner_v(myft, part="all", border = small_border)
myft
```

In my R studio, it shows this, which is what I expect it to be.
![image](https://user-images.githubusercontent.com/61399550/130545936-b45b9d6f-62a6-410b-835d-7f583d5dc706.png)
However, when I open it in my Chrome, it shows this:
![image](https://user-images.githubusercontent.com/61399550/130546045-e44666ce-c0e7-4715-9dc8-a9938ba04ad6.png)

This is also what I saw from the documentation (in Chrome)
![image](https://user-images.githubusercontent.com/61399550/130546110-6d356925-8651-4105-b9bf-84f01c482687.png)

I wonder whether there is anyone else having the same issue? In case this is relevant, my Chrome is Version 92.0.4515.159 (Official Build) (64-bit). I've tried it in Edge and it shows the same results.

sessioninfo:
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mfePubs_0.0.0.9000    shinyBS_0.61          leafsync_0.1.0        statmod_1.4.36        shinybusy_0.2.2      
 [6] tableHTML_2.1.0       flextable_0.6.7       extrafont_0.17        shinydashboard_0.7.1  officer_0.3.19       
[11] aws.s3_0.3.21         shinycssloaders_1.0.0 shinythemes_1.2.0     gridGraphics_0.5-1    ggrepel_0.9.1        
[16] ranger_0.12.1         e1071_1.7-6           caret_6.0-86          lattice_0.20-38       Metrics_0.1.4        
[21] broom_0.7.6           gridExtra_2.3         openair_2.8-3         shinyWidgets_0.6.0    ggpubr_0.4.0         
[26] XML_3.99-0.3          tinytex_0.32          openssl_1.4.4         shinyjs_2.0.0         rpivotTable_0.3.0    
[31] mblm_0.12.1           zoo_1.8-9             expsmooth_2.3         fma_2.4               forecast_8.14        
[36] fpp2_2.4              crosstalk_1.1.1       scales_1.1.1          rsconnect_0.8.18      viridis_0.6.1        
[41] viridisLite_0.4.0     tmap_3.3-1            RColorBrewer_1.1-2    reshape_0.8.8         plotly_4.9.4         
[46] readxl_1.3.1          rgeos_0.5-5           maptools_1.1-1        sf_0.9-8              maps_3.3.0           
[51] ggmap_3.0.0           rgdal_1.5-23          leaflet_2.0.4.1       sp_1.4-5              lubridate_1.7.10     
[56] forcats_0.5.1         stringr_1.4.0         purrr_0.3.4           readr_1.4.0           tidyr_1.1.3          
[61] tibble_3.1.1          ggplot2_3.3.3         tidyverse_1.3.1       dplyr_1.0.6           plyr_1.8.6           
[66] shiny_1.6.0          

loaded via a namespace (and not attached):
  [1] utf8_1.2.1              tidyselect_1.1.1        htmlwidgets_1.5.3       aws.signature_0.6.0    
  [5] pROC_1.17.0.1           munsell_0.5.0           codetools_0.2-16        units_0.7-1            
  [9] DT_0.18                 withr_2.4.2             colorspace_2.0-1        knitr_1.33             
 [13] uuid_0.1-4              rstudioapi_0.13         stats4_3.6.1            ggsignif_0.6.1         
 [17] Rttf2pt1_1.3.8          TTR_0.24.2              RgoogleMaps_1.4.5.3     farver_2.1.0           
 [21] vctrs_0.3.8             generics_0.1.0          ipred_0.9-11            xfun_0.23              
 [25] R6_2.5.0                bitops_1.0-7            cachem_1.0.4            assertthat_0.2.1       
 [29] promises_1.2.0.1        nnet_7.3-12             gtable_0.3.0            lwgeom_0.2-6           
 [33] timeDate_3043.102       rlang_0.4.11            systemfonts_1.0.2       splines_3.6.1          
 [37] extrafontdb_1.0         rstatix_0.7.0           lazyeval_0.2.2          ModelMetrics_1.2.2.2   
 [41] dichromat_2.0-0         hexbin_1.28.2           yaml_2.2.1              reshape2_1.4.4         
 [45] abind_1.4-5             modelr_0.1.8            backports_1.2.1         httpuv_1.6.1           
 [49] quantmod_0.4.18         lava_1.6.9              tools_3.6.1             ellipsis_0.3.2         
 [53] raster_3.4-10           jquerylib_0.1.4         proxy_0.4-25            Rcpp_1.0.6             
 [57] base64enc_0.1-3         classInt_0.4-3          rpart_4.1-15            fracdiff_1.5-1         
 [61] tmaptools_3.1-1         haven_2.4.1             cluster_2.1.0           fs_1.5.0               
 [65] leafem_0.1.6            magrittr_2.0.1          data.table_1.14.0       openxlsx_4.2.3         
 [69] lmtest_0.9-38           reprex_2.0.0            hms_1.1.0               mime_0.10              
 [73] evaluate_0.14           xtable_1.8-4            rio_0.5.26              jpeg_0.1-8.1           
 [77] compiler_3.6.1          KernSmooth_2.23-15      crayon_1.4.1            htmltools_0.5.1.1      
 [81] mgcv_1.8-28             later_1.2.0             DBI_1.1.1               dbplyr_2.1.1           
 [85] MASS_7.3-54             Matrix_1.2-17           car_3.0-10              cli_2.5.0              
 [89] quadprog_1.5-8          parallel_3.6.1          gower_0.2.2             pkgconfig_2.0.3        
 [93] foreign_0.8-71          recipes_0.1.16          xml2_1.3.2              foreach_1.5.1          
 [97] bslib_0.2.5.1           prodlim_2019.11.13      rvest_1.0.0             digest_0.6.27          
[101] rmarkdown_2.8           cellranger_1.1.0        gdtools_0.2.3           curl_4.3.1             
[105] urca_1.3-0              rjson_0.2.20            lifecycle_1.0.0         nlme_3.1-140           
[109] jsonlite_1.7.2          tseries_0.10-48         carData_3.0-4           mapproj_1.2.7          
[113] askpass_1.1             fansi_0.4.2             pillar_1.6.1            survival_2.44-1.1      
[117] fastmap_1.1.0           httr_1.4.2              glue_1.4.2              xts_0.12.1             
[121] zip_2.1.1               png_0.1-7               iterators_1.0.13        leaflet.providers_1.9.0
[125] class_7.3-15            stringi_1.6.1           sass_0.4.0              latticeExtra_0.6-29    
[129] stars_0.5-3

**Comment by davidgohel** [comment] 2021-08-31 23:10
Thank you for reporting this! It should be fixed now.

**Comment by davidgohel** [comment] 2021-09-01 21:59
No it's not

**Comment by davidgohel** [comment] 2022-05-05 12:27
This is an issue with chrome. I can't reproduce anymore since I updated my Chrome version. With old version, I could reproduce but not when printing so I really think it's about the browser (for example, when I zoomed in, the borders were ok)

**Closed by davidgohel** 2022-05-05 12:27 UTC
