### ISSUE TITLE
Problem with linethickness in tables resolved when CTRL+Replace PT to PX

### ISSUE THREAD

**Issue by ltrainstg** [davidgohel/flextable#374] opened 2022-01-25 21:39 UTC
# Problem
The tables made with flextable seem to have lines that are too thick in some places.   (See Image 1)

# Potential resolution
I noticed that if you do a CTRL+Replace on pt to px the issue is resolved. (See Image 2)

# Reprex Code 

```
library(dplyr)
library(flextable)
library(officer)
fp_border <- officer::fp_border()
big_border = fp_border(color="#2c3a51" , width = 2)
std_border = fp_border(color="#2c3a51" , width = 1)
myft <- 
iris %>% flextable() %>% 
  bg(bg = "#00557F", part = "header") %>%
  bold(part = "header") %>%
  color( color = "white", part = "header") %>%
  border_outer(border = big_border, part = "all" ) %>%
  border_inner_h( border = std_border, part = "all" ) %>%
  border_inner_v( border = std_border, part = "all" ) %>% autofit()
myft

myft %>% save_as_html(path = 'ex.html')
```

# Image 1: The Incorrect flextable with some inner lines too thick

![image](https://user-images.githubusercontent.com/16125810/151062733-b952ff51-8627-427e-950c-928c73e01f3d.png)

# Image 2: The Correct flextable after doing a ctrl replace of pt to px

![image](https://user-images.githubusercontent.com/16125810/151063438-8016124d-983b-4f8c-93da-b3f3f475eb1c.png)

# R Session Info 

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gplots_3.1.1            downloadthis_0.2.1      metafor_3.0-2           Matrix_1.3-3           
 [5] knitr_1.33              forcats_0.5.1           stringr_1.4.0           purrr_0.3.4            
 [9] readr_1.4.0             tidyr_1.1.2             tibble_3.0.4            tidyverse_1.3.0        
[13] officedown_0.2.2        DREutils_1.0            pander_0.6.4            ggplot2_3.3.3          
[17] Cairo_1.5-12.2          DREevidenceTables_1.0.0 officer_0.4.1           flextable_0.6.10       
[21] dplyr_1.0.2            

loaded via a namespace (and not attached):
 [1] nlme_3.1-152       bitops_1.0-7       fs_1.5.0           lubridate_1.7.9.2  httr_1.4.2         tools_4.1.0       
 [7] backports_1.2.1    R6_2.5.1           KernSmooth_2.23-20 DBI_1.1.0          colorspace_2.0-0   withr_2.4.3       
[13] tidyselect_1.1.0   compiler_4.1.0     cli_3.1.0          rvest_0.3.6        xml2_1.3.2         bookdown_0.21     
[19] caTools_1.18.2     scales_1.1.1       bsplus_0.1.2       systemfonts_1.0.2  digest_0.6.29      rmarkdown_2.11    
[25] base64enc_0.1-3    pkgconfig_2.0.3    htmltools_0.5.0    dbplyr_2.0.0       fastmap_1.1.0      highr_0.9         
[31] rvg_0.2.5          rlang_0.4.10       readxl_1.3.1       rstudioapi_0.13    jquerylib_0.1.4    generics_0.1.0    
[37] jsonlite_1.7.2     gtools_3.9.2       zip_2.2.0          magrittr_2.0.1     Rcpp_1.0.7         munsell_0.5.0     
[43] gdtools_0.2.3      lifecycle_0.2.0    stringi_1.6.2      yaml_2.2.1         mathjaxr_1.4-0     plyr_1.8.6        
[49] grid_4.1.0         crayon_1.4.2       lattice_0.20-44    haven_2.4.1        hms_1.1.0          pillar_1.4.7      
[55] uuid_0.1-4         reprex_0.3.0       glue_1.4.2         evaluate_0.14      data.table_1.13.6  modelr_0.1.8      
[61] vctrs_0.3.8        rmdformats_1.0.1   cellranger_1.1.0   gtable_0.3.0       assertthat_0.2.1   cachem_1.0.5      
[67] xfun_0.29          mime_0.10          broom_0.7.3        memoise_2.0.0      ellipsis_0.3.2  
``

# The HTML files
Here are the HTML files generated by the above code with the extensions changes since github doesn't allow HTML extensions on attachments. 


[ex_pre.txt](https://github.com/davidgohel/flextable/files/7937344/ex_pre.txt)
[ex_post.txt](https://github.com/davidgohel/flextable/files/7937345/ex_post.txt)
`

**Comment by davidgohel** [comment] 2022-01-26 21:26
Thank you, this is a duplicate of #343

Things can not be solved with your workaround (I tried long ago and retried with your post). 

For example, I can't see any issue when using safari and firefox, but I can see border weird effects on chrome. This can disappear when zooming. It does not occur when printing also.

I think this is a chrome issue, I don't know if there are valid workarounds or a way to understand what is the exact issue.

**Closed by davidgohel** 2022-01-26 21:26 UTC
