### ISSUE TITLE
tables not rendered in rmarkdown with pdf_document

### ISSUE THREAD

**Issue by wolski** [davidgohel/flextable#198] opened 2020-03-12 15:15 UTC
Sorry to bother again . But flextable is not showing up in pdf output.
This is the markdown:

  ---

    title: "Untitled"
    author: "Witold Wolski"
    date: "07/02/2020"
    output:
      pdf_document: default
      html_document: default
    ---
    
    
    
    ```{r}
    library(flextable)
    flextable(cars)
    ```

And thats the output
[test.pdf](https://github.com/davidgohel/flextable/files/4324918/test.pdf)

I am really sorry, but R is such a moving target. I hope you have an idea what I can do. Thanks again for this great package.

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.5.9

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        packrat_0.5.0     digest_0.6.25     R6_2.4.1          magrittr_1.5      evaluate_0.14     zip_2.0.4         rlang_0.4.5       stringi_1.4.6     gdtools_0.2.1     uuid_0.1-4        data.table_1.12.8 xml2_1.2.5       
[14] rmarkdown_2.1     tools_3.6.3       stringr_1.4.0     tinytex_0.20      officer_0.3.7     xfun_0.12         yaml_2.2.1        compiler_3.6.3    systemfonts_0.1.1 base64enc_0.1-3   htmltools_0.4.0   knitr_1.28       


```

**Comment by davidgohel** [comment] 2020-03-12 15:20
Did you install webshot or webshot2?

**Comment by wolski** [comment] 2020-03-12 15:32
I  did install webshot2 using remotes. 
Can load it with:

```
library(webshot2)
```

But still now tables

**Comment by davidgohel** [comment] 2020-03-12 15:42
Can you provide R markdown log?

**Comment by wolski** [comment] 2020-03-12 16:08
I guess because there are no errors there is no log. Can you tell me how to run render so that there are logs left please?

**Comment by davidgohel** [comment] 2020-03-12 16:16
`rmarkdown::render(...)` and then copy the output written in the console

**Comment by wolski** [comment] 2020-03-12 20:13
```
> rmarkdown::render("vignettes/test.Rmd", output_format = "pdf_document")


processing file: test.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1

output file: test.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output test.tex --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --lua-filter "C:/Users/wolski/Documents/R/win-library/3.6/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/Users/wolski/Documents/R/win-library/3.6/rmarkdown/rmd/lua/latex-div.lua" --variable "geometry:margin=1in" 

Output created: test.pdf
> 
```

**Comment by davidgohel** [comment] 2020-03-13 10:09
OK OK,

then I am clueless - I am not able to reproduce and no error, no warning in r markdown log :(

**Comment by davidgohel** [comment] 2020-07-20 22:11
I compared the properties of the document and it seems you are using miktex while I am using tinytex. Could you from a fresh new session install tinytex and run this command:


    tinytex::install_tinytex()

Then follow instructions (restart rstudio or R) and try to render your document?

**Comment by davidgohel** [comment] 2020-11-22 21:55
Closing the issue as latex is now supported (see https://github.com/davidgohel/flextable/commit/d685f8b0a43356453f40ba4bf7824d4ed25029a4)

**Closed by davidgohel** 2020-11-22 21:55 UTC
Labels: help wanted, not reproducible
