### ISSUE TITLE
merge_h(part = "header") cancells autofit()

### ISSUE THREAD

**Issue by fdecarpentier** [davidgohel/flextable#210] opened 2020-04-04 14:25 UTC
Hi David,

Thanks again for this package!

This code works fine: 
```R
library(flextable)
library(tidyverse)

typology <- data.frame(
  col_keys = c( "Sepal.Length", 
                "Sepal.Width", "Petal.Length",
                "Petal.Width", "Species" ),
  type = c("double", "double", "double", 
           "double", "factor"),
  what = c("Sepal", "Sepal", "Petal", 
           "Petal", "Species"),
  measure = c("Length", "Width", "Length", 
              "Width", "Species"),
  stringsAsFactors = FALSE )

ft <- flextable(head(iris)) %>%
  set_header_df(mapping = typology, key = "col_keys" ) %>%
  merge_v(part = "header") %>%
  theme_booktabs() %>%
  autofit() %>%
  fix_border_issues()
ft
```

But if I add  merge_h(part = "header") : 

```R
library(flextable)
library(tidyverse)

typology <- data.frame(
  col_keys = c( "Sepal.Length", 
                "Sepal.Width", "Petal.Length",
                "Petal.Width", "Species" ),
  type = c("double", "double", "double", 
           "double", "factor"),
  what = c("Sepal", "Sepal", "Petal", 
           "Petal", "Species"),
  measure = c("Length", "Width", "Length", 
              "Width", "Species"),
  stringsAsFactors = FALSE )

ft <- flextable(head(iris)) %>%
  set_header_df(mapping = typology, key = "col_keys" ) %>%
  merge_h(part = "header") %>%
  merge_v(part = "header") %>%
  theme_booktabs() %>%
  autofit() %>%
  fix_border_issues()
ft
```
Then autofit() is broken: 
![Rplot](https://user-images.githubusercontent.com/61156192/78453256-c0309900-7690-11ea-846c-e730c506e3e8.png)

Regards,

Félix

**Comment by davidgohel** [comment] 2020-04-08 07:23
Dear Felix,

Next time, try to follow the guidelines (your sessionInfo is missing).

This is what I get with your code.

<img width="311" alt="Capture d’écran 2020-04-08 à 09 20 04" src="https://user-images.githubusercontent.com/4331618/78755893-375c7a80-797a-11ea-94c1-74b89282fd07.png">

Probably a duplicate of #192 ; it's solved but maybe you don't have the github version.

**Closed** 2020-04-08 07:23 UTC
Labels: duplicate
