### ISSUE TITLE
`reference_docx` path changes from `getwd()` only when `flextable()` called in a .Rmd file

### ISSUE THREAD

**Issue by Aariq** [davidgohel/flextable#333] opened 2021-06-25 13:28 UTC
I'm not *exactly* sure what is going on here, but it is related to [this edge case in `tarchetypes`](https://github.com/ropensci/tarchetypes/issues/61).  When `render()` is called with `knit_root_dir = getwd()` a .Rmd file with a `reference_docx` fails to knit **only** when a `flextable()` is output in the document.  Here's a reprex:

``` r
# Set up the files:
# * Rmd source.
# * docx reference.
# * RDS data file.
saveRDS(mtcars, "data.rds")
lines <- c(
  "---",
  "title: 'template'",
  "output: word_document",
  "---",
  "",
  "#heading 1",
  "testing"
)
dir.create("doc/")
writeLines(lines, "doc/template.Rmd")
rmarkdown::render("doc/template.Rmd", output_format = "word_document")
#> processing file: template.Rmd
#> output file: template.knit.md
#> /usr/local/bin/pandoc +RTS -K512m -RTS template.knit.md --to docx --from markdown+autolink_bare_uris+tex_math_single_backslash --output template.docx --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --highlight-style tango
#> 
#> Output created: template.docx

lines <- c(
  "---",
  "title: 'Untitled'",
  "---",
  "",
  "```{r try}",
  "library(flextable)",
  "flextable(readRDS('data.rds'))", # Data file is relative to project root.
  "```"
)
writeLines(lines, "doc/test.Rmd")

# Render with correct root dir and reference at template.docx
# This works when `flextable()` is removed from test.Rmd
library(rmarkdown)
render(
  "doc/test.Rmd",
  knit_root_dir = getwd(),
  output_format = word_document(reference_docx = "template.docx")
)
#> processing file: test.Rmd
#> Quitting from lines 6-8 (test.Rmd)
#> Error: could not find file 'template.docx'


# Render with correct root dir and reference at doc/template.docx
render(
  "doc/test.Rmd",
  knit_root_dir = getwd(),
  output_format = word_document(reference_docx = "doc/template.docx")
)
#> processing file: test.Rmd
#> output file: test.knit.md
#> /usr/local/bin/pandoc +RTS -K512m -RTS test.knit.md --to docx --from markdown+autolink_bare_uris+tex_math_single_backslash --output test.docx --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --highlight-style tango --reference-doc doc/template.docx
#> Error: pandoc document conversion failed with error 1
```

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       macOS  10.16                
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2021-06-25                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.0.2)
#>  base64enc     0.1-3   2015-07-28 [1] CRAN (R 4.0.0)
#>  cli           2.5.0   2021-04-26 [1] CRAN (R 4.0.2)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.2)
#>  data.table    1.14.0  2021-02-21 [1] CRAN (R 4.0.2)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.0.2)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.0.2)
#>  flextable   * 0.6.6   2021-05-17 [1] CRAN (R 4.0.2)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  gdtools       0.2.3   2021-01-06 [1] CRAN (R 4.0.2)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.2)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.2)
#>  knitr         1.33    2021-04-24 [1] CRAN (R 4.0.2)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.2)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
#>  officer       0.3.18  2021-04-02 [1] CRAN (R 4.0.2)
#>  pillar        1.6.1   2021-05-16 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.2)
#>  Rcpp          1.0.6   2021-01-15 [1] CRAN (R 4.0.2)
#>  reprex        2.0.0   2021-04-02 [1] CRAN (R 4.0.2)
#>  rlang         0.4.11  2021-04-30 [1] CRAN (R 4.0.2)
#>  rmarkdown   * 2.9     2021-06-15 [1] CRAN (R 4.0.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.6.2   2021-05-17 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  styler        1.4.1   2021-03-30 [1] CRAN (R 4.0.2)
#>  systemfonts   1.0.2   2021-05-11 [1] CRAN (R 4.0.2)
#>  tibble        3.1.2   2021-05-16 [1] CRAN (R 4.0.2)
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.2)
#>  uuid          0.1-4   2020-02-26 [1] CRAN (R 4.0.2)
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.0.2)
#>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.2)
#>  xfun          0.24    2021-06-15 [1] CRAN (R 4.0.2)
#>  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#>  zip           2.2.0   2021-05-31 [1] CRAN (R 4.0.2)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

**Comment by Aariq** [comment] 2021-06-25 13:28
If you think this is more likely a `rmarkdown` bug, I can cross-post the issue there too.

**Comment by davidgohel** [comment] 2021-07-21 08:20
thanks, I can reproduce.

The issue is that I assumed pandoc `--reference-doc` could be used to let me know where is the `reference_docx`. With the setting you are using, it does not work as the wd changed... It may take times to fix, I don't have solution for now...

**Comment by Aariq** [comment] 2021-07-21 12:42
I kind of think pandoc *should* be able to find the `reference_docx` even when the`knit_root_dir` directory is changed. I couldn't figure out why this only causes an error with `flextable`.  If you have some insight on that, maybe it makes more sense to report this as an `rmarkdown` bug?

**Comment by davidgohel** [comment] 2021-07-21 12:50
No this is not an issue with rmarkdown, I found out after having posted my answer, it was tingling me... It's coming from officer and should be fixed soon. The path of `knitr::opts_knit$get("output.dir")` need to be used in addition to value used in "--reference-doc"

**Comment by davidgohel** [comment] 2021-07-21 18:17
#### This can't work

It's not a rmarkdown bug. It's expected.

> reference_docx is relative to the Rmd file, flextable not involved here

```{r}
saveRDS(mtcars, "data.rds")

lines <- c(
  "---",
  "title: 'Untitled'",
  "---",
  "",
  "# Hi",
  "",
  "```{r try}",
  "readRDS('data.rds')", 
  "```", ""
)
writeLines(lines, "doc/test.Rmd")

render(
  "doc/test.Rmd",
  knit_root_dir = getwd(),
  output_format = word_document(reference_docx = "doc/template.docx")
)
```


#### This works now

with latest officer version (`>=0.3.19`).

```{r}
saveRDS(mtcars, "data.rds")

lines <- c(
  "---",
  "title: 'Untitled'",
  "---",
  "",
  "```{r try}",
  "library(flextable)",
  "flextable(readRDS('data.rds'))", # Data file is relative to project root.
  "```", 
  ""
)

writeLines(lines, "doc/test.Rmd")

render(
  "doc/test.Rmd",
  knit_root_dir = getwd(),
  output_format = word_document(reference_docx = "template.docx")
)
```

**Comment by Aariq** [comment] 2021-07-22 13:59
I just tested it and it works now.  Thanks!

**Comment by davidgohel** [comment] 2021-07-22 14:04
cool, thanks for the feedback!

**Closed** 2021-07-22 14:04 UTC
Labels: bug
