### ISSUE TITLE
digits argument apparently not working

### ISSUE THREAD

**Issue by ebrenc** [davidgohel/flextable#281] opened 2021-01-18 20:24 UTC
Is it possible that the specification of the number of digits has stopped working? I don't know what to do to get them right. Here's part of my code (inside a function):

require(flextable)
  
  set_flextable_defaults(font.family = "Arial", font.size = 9, digits = 3)
  
  results <- results.table %>% flextable() %>% theme_vanilla()
  
  results <- results %>% 
    colformat_num(j = "Df", digits = 0) %>% 
    colformat_num(j = "f1.cohensd", digits = 2) %>% 
    colformat_num(j = "f2.cohensd", digits = 2) %>% 
    colformat_num(j = "f3.cohensd", digits = 2) %>% 
    colformat_num(j = "f4.cohensd", digits = 2)

Thank you!

**Comment by davidgohel** [comment] 2021-01-19 09:07
I can't reproduce. Next time, don't forget to use the guidelines, at minimum:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 


```
library(flextable)
library(magrittr)

set_flextable_defaults(font.family = "Arial", font.size = 9, digits = 3)

results <- head(mtcars) %>% flextable() %>% theme_vanilla()

results <- results %>%
  colformat_num(j = 8:11, digits = 0) %>%
  colformat_num(j = 2:5, digits = 1)
results
```

<img width="1038" alt="Capture d’écran 2021-01-19 à 10 06 40" src="https://user-images.githubusercontent.com/4331618/105012081-08615200-5a3e-11eb-9e25-3fd80fdbbb91.png">

**Comment by davidgohel** [comment] 2021-01-20 11:42
Closing the issue, I will re-open if I can reproduce the issue

**Closed by davidgohel** 2021-01-20 11:42 UTC
Labels: invalid

**Comment by ebrenc** [comment] 2021-01-20 18:00
I works for me now, and I have not touch a thing. It has probably been after restarting of the computer, I really don't know! Thank you anyway!
