### ISSUE TITLE
Wrong data with specific column names

### ISSUE THREAD

**Issue by sstudent** [davidgohel/flextable#44] opened 2017-12-20 19:31 UTC
When the colnames have special keys the generated flextable is wrong.
Example data.frame(a=(c(1))) %>% `colnames<-`('a - b') %>% flextable()
Result: 
{{a - b}}
{{a - b}}
The expected result
  a - b
    1

**Comment by davidgohel** [comment] 2017-12-21 06:55
Please, read #41 as suggested yesterday. Your example is not reproducible. 

1. Could you confirm you tested the code you send me? My base R version does not know about `%>%`. Then I loaded `magrittr` (assuming you just did not care about sending me a reproducible example) but the code is still failing. 

```
> data.frame(a=(c(1))) %>% colnames<-('a - b')
Error in data.frame(a = (c(1))) %>% colnames <- ("a - b") : 
  la cible de l'assignation est un objet n'appartenant pas au langage
```

2. Why did not you provide `sessionInfo()` as requested? (I really need to know)

**Comment by sstudent** [comment] 2017-12-21 08:36
I'm sorry for wasting your time. Here is the example with R base
 library(flextable)
data=data.frame(a=(c(1)))
colnames(data)='a - b'
flextable(data)

sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Europe.1250  LC_CTYPE=English_Europe.1250    LC_MONETARY=English_Europe.1250
[4] LC_NUMERIC=C                    LC_TIME=English_Europe.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.3.0      officer_0.2.1.0001   RevoUtils_10.0.6     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13      bindr_0.1         xml2_1.1.1        magrittr_1.5      uuid_0.1-2        R6_2.2.2         
 [7] rlang_0.1.2       stringr_1.2.0     dplyr_0.7.2       tools_3.4.2       R.oo_1.21.0       htmltools_0.3.6  
[13] yaml_2.1.14       assertthat_0.2.0  lazyeval_0.2.0    digest_0.6.12     tibble_1.3.4      bindrcpp_0.2     
[19] zip_1.0.0.9000    purrr_0.2.3       base64enc_0.1-3   htmlwidgets_0.9   R.utils_2.5.0     glue_1.1.1       
[25] stringi_1.1.5     compiler_3.4.2    gdtools_0.1.6     R.methodsS3_1.7.1 jsonlite_1.4      pkgconfig_2.0.1

**Comment by davidgohel** [comment] 2017-12-21 09:28
OK, 

You need to update from CRAN. The latest version is `0.4.0`. `flextable` does not accept invalid column names (non syntactic names), `regulartable` does accept them, I would use `regulartable` in your case. I will update the documentation about that (but it does not seem crucial as a error is raised when invalid column names are used).

Sorry, I am behaving like a bear:) I need to know why you did not provide `sessionInfo()` because I have to ask it more than 50% of time and I need to understand where should I write that and how should I write about it :) What was you path to this page, did you read the README or help pages before filling an issue or did you only clicked on the BugReports link in the DESCRIPTION file? 

> I rename the column only for this example. My produced data have originally column names like 'a - b'. It is result from anova multiple testing methods.

Using `regulartable` will solve your troubles but be aware you can replace a column name by a label (and much more), see here:
https://davidgohel.github.io/flextable/articles/layout.html#manage-headers

**Comment by davidgohel** [comment] 2017-12-21 11:52
I drop your edit as it makes things hard to understand for other readers.

**Comment by davidgohel** [comment] 2017-12-22 09:16
OK, you don't want to answer but can you close the issue (this can be done by moving your mouse over the "close" button and then clicking on it)?

**Closed** 2017-12-22 10:56 UTC
Labels: invalid
