### ISSUE TITLE
Header does not show up in preview in Rstudio

### ISSUE THREAD

**Issue by yuliaUU** [davidgohel/flextable#305] opened 2021-04-02 18:48 UTC
**Not a bug or feature request? If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**  

When submitting a new issue:

- [x] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [x] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [x] Make sure you searched in the *open* and *closed* issues on the github repository.

So I have issues with the `flextable` header and rounding of digits. Here is the code I use:
My YAML header:

```
---
title: "Test"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: readable
---

```

The code I am trying to run:

```
library(flextable)
library(tidyr)
mtcars %>% flextable()  %>% 
  colformat_num(j = "drat", digits = 1) %>% 
  set_caption(caption = "Summary statistics")
````

the output that shows up after I ran the code: 

![image](https://user-images.githubusercontent.com/54612866/113444781-6a78f480-93a9-11eb-81a0-dbb2306e4ac2.png)

- the issue is the title color is white in preview: so I cant see it
- the rounding for a column drat did not work.

Output of  `sessionInfo()`
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.6.4 tidyr_1.1.3    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        xml2_1.3.2        knitr_1.31        magrittr_2.0.1    uuid_0.1-4        tidyselect_1.1.0  here_1.0.1        R6_2.5.0         
 [9] rlang_0.4.10      dplyr_1.0.5       tools_4.0.3       data.table_1.13.6 xfun_0.22         DBI_1.1.1         systemfonts_1.0.1 htmltools_0.5.1.1
[17] ellipsis_0.3.1    yaml_2.2.1        rprojroot_2.0.2   digest_0.6.27     assertthat_0.2.1  tibble_3.0.6      lifecycle_1.0.0   crayon_1.4.0     
[25] zip_2.1.1         officer_0.3.17    purrr_0.3.4       base64enc_0.1-3   vctrs_0.3.6       glue_1.4.2        evaluate_0.14     rmarkdown_2.7    
[33] compiler_4.0.3    pillar_1.4.7      gdtools_0.2.3     generics_0.1.0    pkgconfig_2.0.3  
```

**Comment by davidgohel** [comment] 2021-04-11 16:16
I tried to reproduce on a windows machine but did not succeed:

`````````

---
title: "Test"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: readable
---

```{r}
library(flextable)
library(tidyr)
mtcars %>% flextable()  %>% 
  colformat_num(j = "drat", digits = 1) %>% 
  set_caption(caption = "Summary statistics")
```

`````````

![Capture](https://user-images.githubusercontent.com/4331618/114312013-6e1b2280-9af1-11eb-8db2-d6032a47ee3f.PNG)

Could you upload the html file please?  You should be able to drag the resulting html file into the comment window. It would be helpful in figuring out what's going on.

**Comment by davidgohel** [comment] 2021-04-11 16:19
For the second question, its because you are using `colformat_num` instead of `colformat_double`. see also #292

**Comment by yuliaUU** [comment] 2021-04-11 16:21
Hi, no need to knit. Just in Rmd file, run a chunk and see the output.

**Comment by davidgohel** [comment] 2021-04-11 16:37
This is a new screenshot from my windows computer.

![Capture](https://user-images.githubusercontent.com/4331618/114312803-3792d700-9af4-11eb-9400-65ba6963b0de.PNG)

**Comment by yuliaUU** [comment] 2021-04-11 16:41
Interesting!... so the issue is just on my side... but I have no idea what can cause it. 
thanks a lot for all your help!

**Comment by davidgohel** [comment] 2021-04-11 16:47
RStudio viewer had issues in the past on Windows platform, could you make sure you have the latest version? 

Could you explain more what you are trying to do? The Last time it was also about caption style. To me, a caption style should not vary along the different tables or figures in a document. That's also the philosophy of R Markdown from my understanding. Maybe you would be more happy with something else than a caption. For example, there is `add_header_lines` and this lines can easily be formated:

https://ardata-fr.github.io/flextable-book/layout-1.html#add-lines-of-text

**Comment by yuliaUU** [comment] 2021-04-11 16:55
I am on Windows indeed. Yes, I checked for updates and I have  Rstudio version Version 1.4.1103

All I want to do is to run a chunk of code and see the output in a preview window in the rmd file:

![image](https://user-images.githubusercontent.com/54612866/114313604-f676d480-9aab-11eb-8d49-2176455ccab8.png)

**Comment by yuliaUU** [comment] 2021-04-11 17:01
I checked 'add_header_lines'. Unfortunately, it is not what I want. I am writing a report so I need to have my titles for the tables ( and later I am planning to figure out how to set the autonumbering of the tables: e.g. Table 1, Table 2, Table 3 and etc)

**Comment by davidgohel** [comment] 2021-04-11 17:17
thanks for the screenshot, it REALLY makes things easier ;)

You are using a dark theme, and your theme is probably not coloring caption titles in white. That's why you don't see the caption, it's black on black

**Comment by yuliaUU** [comment] 2021-04-11 17:21
sorry for the confusion! should have added the screenshot right away.
yes, indeed when I changed a theme the title was visible! Too bad- that dark theme was my favourite:) 


Thanks a lot for your prompt responses and help!

**Comment by davidgohel** [comment] 2021-04-11 17:23
Closing the issue then

**Closed by davidgohel** 2021-04-11 17:23 UTC
