### ISSUE TITLE
Allow Mardown to Format Text

### ISSUE THREAD

**Issue by acircleda** [davidgohel/flextable#269] opened 2020-12-12 21:55 UTC
I am trying to create a simple table of abbreviations for words like CO2, CO2e, etc. In markdown, I would normally write `CO~2~` or similar, which rendsers with the 2 as a subscript for both R Markdown and Kable. However, it just renders with the tildes in Flextable. I could use `compose`, but would have to do that for each subscript included, which would get very tedious. Any support for in-line markdown (e.g. `~, **, __) or Latex?

Having such a feature would make flextable even more flexible!

Here is my example:

```
tribble(~Abbreviation, ~Definition,
        "CO~2~", "carbon dioxide",
        "CO~2~e", "carbon dioxide equivalent") %>%
  flextable()
```

**Comment by atusy** [comment] 2020-12-12 23:53
ftExtra package helps you.
Vignette: https://ftextra.atusy.net/articles/format_columns.html

Also, this is s duplicate of https://github.com/davidgohel/flextable/issues/259

**Comment by davidgohel** [comment] 2020-12-13 11:13
thanks @atusy 

```
library(magrittr)
library(tibble)
library(ftExtra)

tribble(~Abbreviation, ~Definition,
        "CO~2~", "carbon dioxide",
        "CO~2~e", "carbon dioxide equivalent") %>%
  flextable() %>%
  colformat_md()
```

<img width="677" alt="Capture d’écran 2020-12-13 à 12 12 52" src="https://user-images.githubusercontent.com/4331618/102010154-8db95e80-3d3c-11eb-9919-29cea6015f62.png">

**Closed by davidgohel** 2020-12-13 11:13 UTC
