### ISSUE TITLE
Height function not changing cell height in table

### ISSUE THREAD

**Issue by jreid88** [davidgohel/flextable#214] opened 2020-04-28 18:22 UTC
Hello,
I am writing because I am having an issue with the height adjustment in flextable. When I run the following code on a 10 x 24 dataframe with headers

```
RNA.Extraction.Formatted <- flextable(RNA.Extraction.Worksheet)

RNA.Extraction.Formatted <- bold(RNA.Extraction.Formatted, bold = TRUE, part="header")
RNA.Extraction.Formatted <- bold(RNA.Extraction.Formatted, bold = TRUE, j=1)

border.outer = fp_border(color="black", width=2.5)
border.horizontal = fp_border(color="black", width=1.5)
border.verticall = fp_border(color="black", width=1.5)
RNA.Extraction.Formatted <- border_outer(RNA.Extraction.Formatted, border=border.outer, part="all")
RNA.Extraction.Formatted <- border_inner_h(RNA.Extraction.Formatted, part="all", border = border.horizontal)
RNA.Extraction.Formatted <- border_inner_v(RNA.Extraction.Formatted, part="all", border = border.verticall)

RNA.Extraction.Formatted <- align(RNA.Extraction.Formatted, align = "center", part = "all")
```

if I check dim it reads all widths = 0.75 and heights = 0.25.

Then, if I try to adjust the width and height by using:

```
RNA.Extraction.Formatted <- height(RNA.Extraction.Formatted, height =0.34)
RNA.Extraction.Formatted <- width(RNA.Extraction.Formatted, width = 1.1)
```

and check the dim again it reads that that the width has been changed to 1.1 and height has changed to 0.34 for every row _except for the header row_, which reads 0.25. In addition, the height does not appear to be adjusted at all in the table, whereas the width has been changed appropriately. I've checked the code and don't see an issue, although it's certainly possible. I had previously used the autofit function, but removed it and have rerun the code many times since.

**Comment by jreid88** [comment] 2020-04-28 18:23
I'm not sure if this matters but I should also probably note that rows 20-24 are empty. Maybe that is throwing off the height? However, it appears that even if I fill them the height adjustment still does not have an effect.

**Comment by davidgohel** [comment] 2020-04-28 20:40
This is a duplicate of #213, see the answer with `hrule`

**Closed by davidgohel** 2020-04-28 20:40 UTC
