### ISSUE TITLE
Bar charts in flexables.

### ISSUE THREAD

**Issue by LazolaNGC** [davidgohel/flextable#286] opened 2021-01-25 20:40 UTC
I have seen that one can insert mini plots in flextable, according to a  [Flextbale Book](https://ardata-fr.github.io/flextable-book/cell-content-1.html#mini-charts), there are four types are available: ‘box’, ‘line’, ‘points’ and ‘density’. 
Is it possible to have small bar charts instead?

Bar charts of this nature: 
![RPubs - Sparkline - Google Chrome 2021-01-25 22 39](https://user-images.githubusercontent.com/41509690/105763284-4a1e5b00-5f5e-11eb-8c63-f4d0113563af.png)

I want to do this particularly in flextable is because I am generating a Microsoft word report.

**Comment by davidgohel** [comment] 2021-01-25 20:48
Why not using `gg_chunk`?

**Comment by LazolaNGC** [comment] 2021-01-26 09:32
Thanks for such a prompt response, why isn't there a simpleoption like  'bar'?

**Comment by davidgohel** [comment] 2021-01-26 15:07
I am closing the ticket because there is no reproducible example as requested in the guidelines, the ticket has been opened in the repo officer and not in the flex repo. In addition, the questions asked to help understand the bug are not answered, but other questions are asked that look like trolling.

**Closed by davidgohel** 2021-01-26 15:07 UTC
