### ISSUE TITLE
alignment not retained for cell with linebreak in pptx

### ISSUE THREAD

**Issue by lcougnaud** [davidgohel/flextable#100] opened 2019-02-12 13:26 UTC
Thanks for this great flextable package!
I greatly appreciate the linebreak functionality within the cell of a flextable.
However, it seems that the specified alignment is not respected for cell with linebreak in pptx output:

```{r}
ft <- flextable(data.frame(col1 = "cell with\nlinebreak")) %>% 
	add_header(
		col1 = "column with a long header\nand linebreak", top = TRUE
	) %>% 
	align(align = "center", part = "all") %>%
	merge_v(part = "header") %>%
	width(width = 6)
```

In Powerpoint output, the text before line-break is left-aligned and the text after the line-break is correctly centered: 
`print(ft, preview = "pptx")`:
![columnlinebreakpptx](https://user-images.githubusercontent.com/15339154/52638184-ad2d9900-2ed1-11e9-975a-6f8ef047325c.png)

In Word output, the text is correctly centered:
`print(ft, preview = "docx")`:
![columnlinebreakdocx](https://user-images.githubusercontent.com/15339154/52638213-bf0f3c00-2ed1-11e9-9a08-8acf30ff75a4.png)

Would you know by chance the reason of this difference?

(test with `flextable` version 0.5.2.3)

**Comment by davidgohel** [comment] 2019-02-14 21:14
Sorry I can't reproduce this, can you read the attached powerpoint? It has been generated on my computer and it looks fine to me:

[fileadcc11940a8.pptx](https://github.com/davidgohel/flextable/files/2866820/fileadcc11940a8.pptx)

Could you paste here your `sessionInfo()` and the produced powerpoint?

David

**Comment by lcougnaud** [comment] 2019-02-15 15:36
Here is my sessionInfo:

R version 3.5.1 (2018-07-02)

 Platform: x86_64-pc-linux-gnu (64-bit)

 Running under: Ubuntu 16.04.5 LTS

 Matrix products: default

 BLAS: /usr/lib/libblas/libblas.so.3.6.0

 LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

 * locale:
 LC_ADDRESS=en_GB.UTF-8, LC_COLLATE=en_US.UTF-8, LC_CTYPE=en_US.UTF-8, LC_IDENTIFICATION=en_GB.UTF-8, LC_MEASUREMENT=en_GB.UTF-8, LC_MESSAGES=en_US.UTF-8, LC_MONETARY=en_GB.UTF-8, LC_NAME=en_GB.UTF-8, LC_NUMERIC=C, LC_PAPER=en_GB.UTF-8, LC_TELEPHONE=en_GB.UTF-8, LC_TIME=en_GB.UTF-8

 * attached base packages:
 base, datasets, graphics, grDevices, methods, stats, utils

 * other attached packages:
 devtools_2.0.1, flextable_0.5.2.004, ggplot2_3.1.0, glpgStyle_0.4.0, glpgUtilityFct_0.0.6, inTextSummaryTable_1.0.0, knitr_1.20, magrittr_1.5, oaReporting_0.0.6, pander_0.6.2, rj_3.0.0-13, roxygen2_6.1.0, testthat_2.0.1, usethis_1.4.0, xtable_1.8-3

 * loaded via a namespace (and not attached):
 assertthat_0.2.0, backports_1.1.2, base64enc_0.1-3, bindr_0.1.1, bindrcpp_0.2.2, bookdown_0.7, callr_3.0.0, cli_1.0.1, colorspace_1.3-2, commonmark_1.6, compiler_3.5.1, cowplot_0.9.99, crayon_1.3.4, data.table_1.11.8, desc_1.2.0, digest_0.6.18, dplyr_0.7.7, evaluate_0.11, forcats_0.3.0, fs_1.2.6, gdtools_0.1.7, ggrepel_0.8.0, glue_1.3.0, grid_3.5.1, gtable_0.2.0, haven_2.0.0, hms_0.4.2, htmltools_0.3.6, labeling_0.3, lazyeval_0.2.1, magick_2.0, memoise_1.1.0, munsell_0.5.0, officer_0.3.2, pillar_1.3.1, pkgbuild_1.0.2, pkgconfig_2.0.2, pkgload_1.0.1, plyr_1.8.4, prettyunits_1.0.2, processx_3.2.0, ps_1.2.0, purrr_0.2.5, R6_2.3.0, Rcpp_0.12.19, readr_1.1.1, remotes_2.0.1, reshape2_1.4.3, rj.gd_3.0.0-10, rlang_0.3.0.1, rmarkdown_1.11, rprojroot_1.3-2, scales_1.0.0, sessioninfo_1.1.0, stringi_1.2.4, stringr_1.3.1, tibble_1.4.2, tidyselect_0.2.5, tools_3.5.1, uuid_0.1-2, viridisLite_0.3.0, withr_2.1.2, xfun_0.3, xml2_1.2.0, yaml_2.2.0, zip_1.0.0

* Bioconductor (BiocInstaller) version: 1.30.0 

And the resulting PowerPoint:
[testIssueLinefeedPowerPoint.pptx](https://github.com/davidgohel/flextable/files/2869800/testIssueLinefeedPowerPoint.pptx)

Thanks in advance!

**Comment by davidgohel** [comment] 2019-02-15 17:27
thanks, I'll have a try on a docker machine. The table should not be gray neither... I don't know yet what is the issue

David

**Comment by lcougnaud** [comment] 2019-03-11 12:19
Hi David,
An update concerning the alignment, the alignment is fine when the file is opened with PowerPoint (version 2013), but fails with LibreOffice Impress (version 5.1.6.2).

**Comment by davidgohel** [comment] 2019-03-13 16:42
Hi,

OK, if you don't mind, then I will close this issue. There is no support for libreoffice, only HTML, Word and PowerPoint.

KR
David

**Closed by davidgohel** 2019-03-13 16:42 UTC
